services:
  - type: web
    name: employee-attrition-predictor
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
